
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140902 (SVN rev 60)
//----------------------------------------------------

package ar.edu.itba.geb.compiler.java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 22;
  public static final int DIVEQ = 32;
  public static final int STRING_LITERAL = 57;
  public static final int GTEQ = 27;
  public static final int MULT = 44;
  public static final int LTEQ = 26;
  public static final int MODEQ = 33;
  public static final int SEMI = 46;
  public static final int INT = 10;
  public static final int MINUS = 43;
  public static final int STATIC = 4;
  public static final int OROR = 34;
  public static final int NOT = 36;
  public static final int LT = 38;
  public static final int RPAR = 52;
  public static final int COMMA = 47;
  public static final int BOOL = 11;
  public static final int CLASS = 2;
  public static final int DIV = 40;
  public static final int ANDAND = 24;
  public static final int PLUSEQ = 29;
  public static final int MINUSEQ = 30;
  public static final int PLUS = 42;
  public static final int NULL_LITERAL = 58;
  public static final int MAIN = 6;
  public static final int IF = 12;
  public static final int THIS = 20;
  public static final int DOT = 45;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 23;
  public static final int RETURN = 9;
  public static final int TRUE = 18;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int EQEQ = 25;
  public static final int MOD = 41;
  public static final int MULTEQ = 31;
  public static final int IDENT = 55;
  public static final int VOID = 5;
  public static final int EQ = 37;
  public static final int LBRACK = 53;
  public static final int COLON = 48;
  public static final int LBRACE = 49;
  public static final int ELSE = 13;
  public static final int RBRACK = 54;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int RBRACE = 50;
  public static final int EXTENDS = 8;
  public static final int LPAR = 51;
  public static final int QUESTION = 35;
  public static final int STRING = 7;
  public static final int FALSE = 19;
  public static final int GT = 39;
  public static final int PRINT = 16;
  public static final int LENGTH = 17;
  public static final int DO = 15;
  public static final int NOTEQ = 28;
  public static final int INTEGER_LITERAL = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "EXTENDS",
  "RETURN",
  "INT",
  "BOOL",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "PRINT",
  "LENGTH",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "PLUSPLUS",
  "MINUSMINUS",
  "ANDAND",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "OROR",
  "QUESTION",
  "NOT",
  "EQ",
  "LT",
  "GT",
  "DIV",
  "MOD",
  "PLUS",
  "MINUS",
  "MULT",
  "DOT",
  "SEMI",
  "COMMA",
  "COLON",
  "LBRACE",
  "RBRACE",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "IDENT",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "NULL_LITERAL"
  };
}

